version: '3.8'

services:
  ponder:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vault-ponder-indexer
    ports:
      - "42069:42069"
    environment:
      # Network configuration
      NETWORK: ${NETWORK:-base-sepolia}
      CHAIN_ID: ${CHAIN_ID:-84532}
      
      # RPC configuration
      RPC_URL: ${RPC_URL:-https://base-sepolia.g.alchemy.com/v2/YOUR_KEY}
      
      # Database configuration
      DATABASE_URL: ${DATABASE_URL:-postgresql://user:password@localhost:5432/ponder}
      
      # Contract addresses (Base Sepolia defaults)
      VAULT_ADDRESS: ${VAULT_ADDRESS:-0x73E27097221d4d9D5893a83350dC7A967b46fab7}
      QUEUE_ADDRESS: ${QUEUE_ADDRESS:-0x22BC73098CE1Ba2CaE5431fb32051cB4fc0F9C52}
      REGISTRY_ADDRESS: ${REGISTRY_ADDRESS:-0x15a9983784617aa8892b2677bbaEc23539482B65}
      STRATEGY_ADDRESS: ${STRATEGY_ADDRESS:-0x740907524EbD6A481a81cE76B5115A4cDDb80099}
      PRICE_ORACLE_ADDRESS: ${PRICE_ORACLE_ADDRESS:-0xDB4479A2360E118CCbD99B88e82522813BDE48f5}
      
      # Monitoring
      HEALTH_CHECK_ENABLED: ${HEALTH_CHECK_ENABLED:-true}
      LOG_LEVEL: ${LOG_LEVEL:-info}
      
    restart: unless-stopped
    networks:
      - ponder-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:42069/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Optional: Local PostgreSQL for development
  postgres:
    image: postgres:15-alpine
    container_name: vault-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-ponder}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ponder123}
      POSTGRES_DB: ${POSTGRES_DB:-vault_indexer}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ponder-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ponder"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  ponder-network:
    driver: bridge

volumes:
  postgres_data: