# Railway Configuration for Ponder Indexer

[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"
watchPatterns = ["src/**", "abis/**", "ponder.*.ts", "package.json"]

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
region = "us-west1"

[deploy.scaling]
minInstances = 1
maxInstances = 3
targetCPUPercent = 70
targetMemoryPercent = 80

[services.ponder]
internalPort = 42069
protocol = "http"

[services.ponder.domains]
production = ["indexer.yourdomain.com"]
staging = ["indexer-staging.yourdomain.com"]

[services.ponder.healthcheck]
type = "http"
path = "/health"
interval = 30
timeout = 10
retries = 3

[services.ponder.resources]
cpu = "0.5"
memory = "512Mi"

[services.ponder.autoscaling]
enabled = true
min = 1
max = 3
targetCPU = 70
targetMemory = 80

[environments.production]
variables = { NETWORK = "base", CHAIN_ID = "8453", LOG_LEVEL = "info" }

[environments.staging]
variables = { NETWORK = "base-sepolia", CHAIN_ID = "84532", LOG_LEVEL = "debug" }