version: '3.8'

services:
  # Scheduler service for cron jobs
  scheduler:
    build:
      context: .
      dockerfile: Dockerfile.scheduler
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      DATABASE_URL: ${DATABASE_URL}
      DIRECT_DATABASE_URL: ${DIRECT_DATABASE_URL}
      BASE_SEPOLIA_RPC_URL: ${BASE_SEPOLIA_RPC_URL}
      BASE_RPC_URL: ${BASE_RPC_URL}
      ETHEREUM_RPC_URL: ${ETHEREUM_RPC_URL}
      ARBITRUM_RPC_URL: ${ARBITRUM_RPC_URL}
      OPTIMISM_RPC_URL: ${OPTIMISM_RPC_URL}
      SCHEDULER_PORT: 3001
    ports:
      - "3001:3001"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - sovabtc-network
    depends_on:
      - postgres

  # Ponder indexer for blockchain events
  indexer:
    build:
      context: .
      dockerfile: Dockerfile.indexer
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      NETWORK: ${NETWORK:-baseSepolia}
      DATABASE_URL: ${DATABASE_URL}
      PONDER_DATABASE_URL: ${PONDER_DATABASE_URL:-${DATABASE_URL}}
      BASE_SEPOLIA_RPC_URL: ${BASE_SEPOLIA_RPC_URL}
      BASE_RPC_URL: ${BASE_RPC_URL}
      BASE_VAULT_TOKEN_ADDRESS: ${BASE_VAULT_TOKEN_ADDRESS}
      BASE_VAULT_STRATEGY_ADDRESS: ${BASE_VAULT_STRATEGY_ADDRESS}
      BASE_START_BLOCK: ${BASE_START_BLOCK:-0}
    ports:
      - "42069:42069"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:42069/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - sovabtc-network
    depends_on:
      - postgres

  # PostgreSQL database (optional for local development)
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-sovabtc}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-sovabtc123}
      POSTGRES_DB: ${POSTGRES_DB:-sovabtc}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-sovabtc}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - sovabtc-network

  # Next.js frontend (optional for full stack development)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      DATABASE_URL: postgresql://${POSTGRES_USER:-sovabtc}:${POSTGRES_PASSWORD:-sovabtc123}@postgres:5432/${POSTGRES_DB:-sovabtc}
      DIRECT_DATABASE_URL: postgresql://${POSTGRES_USER:-sovabtc}:${POSTGRES_PASSWORD:-sovabtc123}@postgres:5432/${POSTGRES_DB:-sovabtc}
      NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID: ${NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID}
      NEXT_PUBLIC_BASE_SEPOLIA_RPC: ${NEXT_PUBLIC_BASE_SEPOLIA_RPC}
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - sovabtc-network
    depends_on:
      - postgres
      - scheduler
      - indexer

networks:
  sovabtc-network:
    driver: bridge

volumes:
  postgres-data: