[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "solady/=lib/solady/src/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/"
]
solc = "0.8.25"
fs_permissions = [
    { access = "read-write", path = "./deployments" },
    { access = "read", path = "./deployment.config.json" }
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

optimizer = true
optimizer_runs = 200

rpc_url = "https://rpc.testnet.sova.io"

no_match_coverage = "(script/|test/|mocks/|src/token/tRWA.sol|src/token/GatedMintRWA.sol|src/hooks/RulesEngine.sol|src/strategy/GatedMintEscrow.sol|src/reporter/PriceOracleReporter.sol)"

[rpc_endpoints]
base-sepolia = "https://base-sepolia.drpc.org"

[etherscan]
base-sepolia = { key = "${ETHERSCAN_API_KEY}" }

[profile.coverage]
optimizer = true
optimizer_runs = 1
via_ir = false

[lint]
exclude_lints = ["mixed-case-function", "mixed-case-variable", "unwrapped-modifier-logic"]
